### ISSUE TITLE
make: make: Operation not permitted 

### ISSUE THREAD

**Issue by fengzhao** [robvanoostenrijk/openconnect-server-static#1]
```shell

config.status: linking x86_64/ecc-curve448-modp.asm to ecc-curve448-modp.asm
configure: summary of build options:

  Version:           nettle 3.7.3
  Host type:         x86_64-pc-linux-musl
  ABI:               64
  Assembly files:    x86_64/fat x86_64
  Install prefix:    /usr/local
  Library directory: ${exec_prefix}/lib
  Compiler:          gcc
  Static libraries:  yes
  Shared libraries:  no
  Public key crypto: yes
  Using mini-gmp:    yes
  Documentation:     no

+ sed 's|cnd-copy\.c |&cnd-memcpy.c |' Makefile -i
+ nproc
+ make -j4 install
make install-here
make: make: Operation not permitted
make: *** [Makefile:48: install] Error 127
The command '/bin/sh -c set -x && 	curl --location --silent --output /build/nettle-${NETTLE_VERSION}.tar.gz "https://ftp.gnu.org/gnu/nettle/nettle-${NETTLE_VERSION}.tar.gz" && 	curl --location --silent --compressed --output /build/nettle-${NETTLE_VERSION}.tar.gz.sig "https://ftp.gnu.org/gnu/nettle/nettle-${NETTLE_VERSION}.tar.gz.sig" && 	gpg --verify /build/nettle-${NETTLE_VERSION}.ta
```

**Comment by rob-ek** [comment]
I tested this on both Docker for Mac and Docker on a Linux Alpine host, no errors encountered.

Docker on Mac: `3.6.0`
Docker on Alpine: `Docker version 20.10.7, build f0df35096d5f5e6b559b42c7fde6c65a2909f7c5`

However, based on your feedback, I've reduced the number of file installations for each Make command.
This might resolve your issue.

**Comment by robvanoostenrijk** [comment]
I tested this on both Docker for Mac and Docker on a Linux Alpine host, no errors encountered.

Docker on Mac: `3.6.0`
Docker on Alpine: `Docker version 20.10.7, build f0df35096d5f5e6b559b42c7fde6c65a2909f7c5`

However, based on your feedback, I've reduced the number of file installations for each Make command (beb3e17b329636e423095f5728eaab618d202d34)
This might resolve your issue.

**Comment by robvanoostenrijk** [comment]
Repository is now building an automatic docker image and release as part of GitHub action, so in case of issues you can use the pre-built binaries.
