### ISSUE TITLE
1.2.4 构建文件错误

### ISSUE THREAD

**Issue by ixmu** [robvanoostenrijk/openconnect-server-static#2]
1.2.4构建镜像有问题，应该是进行了大改
[openconnect-server-linux-amd64.tar.xz](https://github.com/robvanoostenrijk/openconnect-server-static/releases/download/v1.3.0/openconnect-server-linux-amd64.tar.xz)
108 Bytes
May 31

**Comment by robvanoostenrijk** [comment]
@ixmu, This is resolved now in updated 1.3.0 build.
